"""test

Revision ID: 8e7cee875e0a
Revises: ae9d8de9ec9f
Create Date: 2024-08-06 13:22:31.636446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7cee875e0a'
down_revision: Union[str, None] = 'ae9d8de9ec9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_id', table_name='product')
    op.drop_index('ix_product_name', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_category_id', table_name='category')
    op.drop_index('ix_category_name', table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_category_name', 'category', ['name'], unique=False)
    op.create_index('ix_category_id', 'category', ['id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_name', 'product', ['name'], unique=False)
    op.create_index('ix_product_id', 'product', ['id'], unique=False)
    # ### end Alembic commands ###
